// SPDX-License-Identifier: GPL-3.0-or-later
//
// agnus_spritedma sprite-select MULTIPLEX bench, under realistic multi-sprite load.
//
// QUESTION UNDER TEST
// -------------------
// The 8 sprites' vertical comparators in rtl/agnus_spritedma.v are not eight
// parallel instances. They are ONE shared comparator time-multiplexed by a
// free-running 28 MHz scan counter:
//
//   always @ (posedge clk) if (sprsel[2]==hpos[0]) sprsel <= sprsel + 1'b1;   // :138
//   assign vstart[7:0] = sprpos[sprsel];                                      // :213
//   assign {vstop[7:0],...} = sprctl[sprsel];                                 // :225
//   always @ (posedge clk) dmastate_mem[sprsel] <= dmastate_in;               // :234
//   assign dmastate = dmastate_mem[sprsel];                                   // :238
//   always @ (posedge clk) if (sprite==sprsel && hpos[2:1]==2'b01)
//     sprdmastate <= dmastate & ~(...);                                       // :250
//   always @ (posedge clk) if (sprite==sprsel && hpos[2:1]==2'b01)
//     sprvstop <= (vstop==vpos);                                              // :255
//
// This is the one structural piece of the sprite DMA design with no real-Agnus
// analogue. If the scan cannot serve all 8 slots inside the window where the
// per-sprite results have to be ready, a sprite's DMA decision would be made
// from STALE data or from a NEIGHBOUR's comparison, and the margin would shrink
// as more sprites go live. That is the "fine with a few sprites, breaks with
// many" signature of the Hybris reward-screen jitter.
//
// METHOD
// ------
// Real amiga_clk + real agnus_beamcounter (sim shim) + real, unmodified
// agnus_spritedma. Four independent DUT environments run concurrently off one
// beamcounter, with 1 / 3 / 6 / 8 simultaneously active sprites, so error rate
// and margin can be compared directly across sprite count.
//
// Each environment is a closed sprite-DMA loop, not a stub: a chip-RAM model
// holds real sprite lists, ackdma is granted on every request, the fetched word
// is fed back on data_in with reg_address_in = reg_address_out (exactly what
// agnus.v does on ack_spr), so SPRxPOS/SPRxCTL are loaded BY DMA and the
// pointer walks the list. A copper-style SPRxPT reload runs each vblank.
//
// STIMULUS = MEASURED HYBRIS REWARD-SCREEN DATA
// ---------------------------------------------
// From research/tmp/hybris_r17/spr3.txt + spr4.txt (WinUAE cycle-exact sprite
// DMA trace of the reward screen, frames 6410-7412), decoded:
//   - sprites 0..5 active, 6 and 7 parked on a terminator entry
//   - each active sprite's 1 KB block holds EIGHT list entries, 36 bytes apart
//     = 2 control words + 8 scanlines x 2 data words
//   - all six sprites share IDENTICAL VSTART/VSTOP; they differ only in HSTART
//   - entry i: VSTART = base + 22*i, VSTOP = VSTART + 8
//   - the table scrolls, so `base` walks (f6411 base=99, f6450 base=85,
//     f7331 base=217). This bench walks base every frame to sweep every phase
//     of the vertical compare against the beam.
//
// PASS = every sprite DMA slot in every line of every frame matches an ideal
// 8-PARALLEL-comparator reference model, for all four sprite counts.
//
// The reference is deliberately NOT a copy of the mux: it keeps 8 independent
// vstart/vstop/dmastate sets and latches each sprite's result on its own enable,
// which is what the hardware the RTL is emulating would do.
//
// NEGATIVE CONTROL: run_sprite_mux_mutant.do compiles mutants generated by
// patch_sprmux_mutant.py (latch window off by one sprite slot, adjacent-slot
// aliasing, broken scan lock, scan running 4x too slow) and this same bench
// must FAIL on each of them.

`timescale 1ns / 1ps

// ===========================================================================
// One DUT + chip RAM + reference model, parameterised by active sprite count.
// ===========================================================================
module spr_env #(
	parameter integer NACT = 6,     // simultaneously active sprites
	parameter integer STAG = 0      // per-sprite VSTART stagger, in scanlines
) (
	input               clk,
	input               clk7_en,
	input               reset,
	input        [8:0]  hpos,
	input        [10:0] vpos,
	input               vbl,
	input               vblend,
	input               run,
	output       [31:0] errs,
	output       [31:0] slots_checked,
	output       [31:0] fetches_pos,
	output       [31:0] fetches_dat
);

localparam [20:1] SPRBASE_W = 20'h08000;    // $010000 >> 1
localparam integer BLKW     = 'h200;        // $400 bytes = 512 words
localparam integer ENTW     = 18;           // 36 bytes  = 18 words

// ------------------------------------------------------------------ chip RAM
reg [15:0] cram [0:8*BLKW-1];

// -------------------------------------------------------------------- the DUT
wire        reqdma;
wire [8:1]  reg_address_out;
wire [20:1] address_out;

reg  [8:1]  reg_address_in;
reg  [15:0] data_in;

reg         spren = 1'b0;
wire        ackdma = reqdma & spren;

agnus_spritedma u_spr (
	.clk             (clk),
	.clk7_en         (clk7_en),
	.reset           (reset),
	.aga             (1'b0),          // Hybris is OCS
	.ecs             (1'b0),
	.reqdma          (reqdma),
	.ackdma          (ackdma),
	.hpos            (hpos),
	.vpos            (vpos),
	.vbl             (vbl),
	.vblend          (vblend),
	.reg_address_in  (reg_address_in),
	.reg_address_out (reg_address_out),
	.data_in         (data_in),
	.address_out     (address_out)
);

// ------------------------------------------- bus: DMA loopback + copper writes
// agnus.v drives reg_address = reg_address_spr and ack_spr = 1 on a granted
// sprite slot, and the chip RAM word arrives on data_in in the same bus cycle.
reg  [8:1]  cop_addr = 8'hFF;
reg  [15:0] cop_data = 16'h0000;

wire [31:0] cram_idx = {12'd0, address_out} - {12'd0, SPRBASE_W};
wire [15:0] cram_q   = (cram_idx < 8*BLKW) ? cram[cram_idx[12:0]] : 16'h0000;

always @(*) begin
	if (ackdma) begin
		reg_address_in = reg_address_out;
		data_in        = cram_q;
	end else begin
		reg_address_in = cop_addr;
		data_in        = cop_data;
	end
end

// ===========================================================================
// REFERENCE MODEL -- eight independent comparators, no shared scan.
// ===========================================================================
reg  [9:0]  ref_vstart [0:7];
reg  [9:0]  ref_vstop  [0:7];
reg         ref_dma    [0:7];   // continuously evaluated per-sprite dma state
reg         ref_sprdma [0:7];   // per-sprite latched copy
reg         ref_svstop [0:7];
reg  [20:1] ref_ptr    [0:7];

// tb-side copy of the slot's sprite number, computed from hpos alone.
reg  [2:0]  tb_sprite = 3'd0;
always @(posedge clk) if (clk7_en && hpos[2:0]==3'b001)
	tb_sprite <= {hpos[5]^hpos[4], ~hpos[4], hpos[3]};

// tb-side copy of the sprite DMA window.
reg tb_enable = 1'b0;
always @(posedge clk) if (clk7_en) begin
	if      (hpos[8:1]==8'h18 && hpos[0]) tb_enable <= 1'b1;
	else if (hpos[8:1]==8'h38 && hpos[0]) tb_enable <= 1'b0;
end

// Register decode, independent of the DUT's internal ptsel/pcsel.
wire        w_ptr    = (reg_address_in[8:5]==4'h9);       // $120-$13E
wire        w_posctl = (reg_address_in[8:6]==3'b101);     // $140-$17E
wire [2:0]  w_pt_sel = reg_address_in[4:2];
wire [2:0]  w_pc_sel = ackdma ? tb_sprite : reg_address_in[5:3];
wire [20:1] ref_newptr = ref_ptr[tb_sprite] + 20'd1;      // fmode = 0

integer i;
always @(posedge clk) begin
	if (clk7_en) begin
		if (ackdma)
			ref_ptr[tb_sprite] <= ref_newptr;
		else if (w_ptr && !reg_address_in[1])
			ref_ptr[w_pt_sel][20:16] <= data_in[4:0];
		else if (w_ptr &&  reg_address_in[1])
			ref_ptr[w_pt_sel][15:1]  <= data_in[15:1];

		if (w_posctl && reg_address_in[2:1]==2'b00)
			ref_vstart[w_pc_sel][7:0] <= data_in[15:8];
		if (w_posctl && reg_address_in[2:1]==2'b01) begin
			ref_vstop [w_pc_sel][7:0] <= data_in[15:8];
			ref_vstart[w_pc_sel][9]   <= data_in[6];
			ref_vstop [w_pc_sel][9]   <= data_in[5];
			ref_vstart[w_pc_sel][8]   <= data_in[2];
			ref_vstop [w_pc_sel][8]   <= data_in[1];
		end
	end
end

// Continuous per-sprite DMA state -- 8 parallel copies of the RTL's rule.
// ecs = 0, so vstart[9]/vstop[9] are masked out of the compare.
always @(posedge clk) begin
	for (i = 0; i < 8; i = i + 1) begin
		if (vbl || ({1'b0, ref_vstop[i][8:0]} == vpos[9:0]))
			ref_dma[i] <= 1'b0;
		else if ({1'b0, ref_vstart[i][8:0]} == vpos[9:0])
			ref_dma[i] <= 1'b1;
	end
end

// Per-sprite latch, each on its OWN enable. No shared scan slot.
always @(posedge clk) begin
	if (hpos[2:1]==2'b01) begin
		ref_sprdma[tb_sprite] <= ref_dma[tb_sprite];
		ref_svstop[tb_sprite] <= ({1'b0, ref_vstop[tb_sprite][8:0]} == vpos[9:0]);
	end
end

// ===========================================================================
// CHECKER -- every sprite DMA slot of every line.
// ===========================================================================
integer e_cnt = 0, s_cnt = 0, f_pos = 0, f_dat = 0, rpt = 0;
assign errs          = e_cnt;
assign slots_checked = s_cnt;
assign fetches_pos   = f_pos;
assign fetches_dat   = f_dat;

wire slot_now = clk7_en && tb_enable && (hpos[1:0]==2'b01);

reg        exp_req;
reg [8:1]  exp_addr;

always @(*) begin
	if (vblend || (ref_svstop[tb_sprite] && ~vbl)) begin
		exp_req  = 1'b1;
		exp_addr = hpos[2] ? {3'b101, tb_sprite, 2'b00} : {3'b101, tb_sprite, 2'b01};
	end else if (ref_sprdma[tb_sprite]) begin
		exp_req  = 1'b1;
		exp_addr = hpos[2] ? {3'b101, tb_sprite, 2'b10} : {3'b101, tb_sprite, 2'b11};
	end else begin
		exp_req  = 1'b0;
		exp_addr = 8'hFF;
	end
end

always @(posedge clk) if (run && !reset) begin
	if (u_spr.sprite !== tb_sprite) begin
		e_cnt <= e_cnt + 1;
		if (rpt < 10) begin
			$display("  [N=%0d] SPRITE-IDX vpos=%0d hpos=%0h dut=%0d tb=%0d",
			         NACT, vpos, hpos, u_spr.sprite, tb_sprite);
			rpt <= rpt + 1;
		end
	end else if (u_spr.enable !== tb_enable) begin
		e_cnt <= e_cnt + 1;
		if (rpt < 10) begin
			$display("  [N=%0d] ENABLE     vpos=%0d hpos=%0h dut=%0d tb=%0d",
			         NACT, vpos, hpos, u_spr.enable, tb_enable);
			rpt <= rpt + 1;
		end
	end else if (slot_now) begin
		s_cnt <= s_cnt + 1;
		if (exp_req) begin
			if (exp_addr[2] == 1'b0) f_pos <= f_pos + 1;
			else                     f_dat <= f_dat + 1;
		end
		if (reqdma !== exp_req) begin
			e_cnt <= e_cnt + 1;
			if (rpt < 10) begin
				$display("  [N=%0d] REQDMA   vpos=%0d hpos=%0h spr%0d dut=%0b ref=%0b  (sprdma d=%0b r=%0b, svstop d=%0b r=%0b)",
				         NACT, vpos, hpos, tb_sprite, reqdma, exp_req,
				         u_spr.sprdmastate, ref_sprdma[tb_sprite],
				         u_spr.sprvstop,    ref_svstop[tb_sprite]);
				rpt <= rpt + 1;
			end
		end else if (exp_req && (reg_address_out !== exp_addr)) begin
			e_cnt <= e_cnt + 1;
			if (rpt < 10) begin
				$display("  [N=%0d] REGADDR  vpos=%0d hpos=%0h spr%0d dut=%0h ref=%0h",
				         NACT, vpos, hpos, tb_sprite, reg_address_out, exp_addr);
				rpt <= rpt + 1;
			end
		end else if (exp_req && (address_out !== ref_ptr[tb_sprite])) begin
			e_cnt <= e_cnt + 1;
			if (rpt < 10) begin
				$display("  [N=%0d] POINTER  vpos=%0d hpos=%0h spr%0d dut=%05h ref=%05h",
				         NACT, vpos, hpos, tb_sprite, address_out, ref_ptr[tb_sprite]);
				rpt <= rpt + 1;
			end
		end else if (u_spr.sprdmastate !== ref_sprdma[tb_sprite]) begin
			e_cnt <= e_cnt + 1;
			if (rpt < 10) begin
				$display("  [N=%0d] SPRDMA   vpos=%0d hpos=%0h spr%0d dut=%0b ref=%0b",
				         NACT, vpos, hpos, tb_sprite, u_spr.sprdmastate, ref_sprdma[tb_sprite]);
				rpt <= rpt + 1;
			end
		end else if (u_spr.sprvstop !== ref_svstop[tb_sprite]) begin
			e_cnt <= e_cnt + 1;
			if (rpt < 10) begin
				$display("  [N=%0d] SPRVSTOP vpos=%0d hpos=%0h spr%0d dut=%0b ref=%0b",
				         NACT, vpos, hpos, tb_sprite, u_spr.sprvstop, ref_svstop[tb_sprite]);
				rpt <= rpt + 1;
			end
		end
	end
end

// ===========================================================================
// Sprite list authoring + the copper's per-frame SPRxPT reload.
// ===========================================================================
function [15:0] mk_pos (input [9:0] vs_, input [8:0] hs_);
	mk_pos = {vs_[7:0], hs_[8:1]};
endfunction

function [15:0] mk_ctl (input [9:0] vs_, input [9:0] ve_, input [8:0] hs_);
	mk_ctl = {ve_[7:0], 1'b0, vs_[9], ve_[9], 2'b00, vs_[8], ve_[8], hs_[0]};
endfunction

integer s, en, w;
reg [9:0] vs, ve;
reg [8:0] hs;

task build_lists (input [8:0] base);
	begin
		for (s = 0; s < 8; s = s + 1) begin
			hs = 9'h040 + s*9'h018;
			for (en = 0; en < 8; en = en + 1) begin
				if (s < NACT) begin
					vs = base + en*22 + s*STAG;
					ve = vs + 8;
					cram[s*BLKW + en*ENTW + 0] = mk_pos(vs, hs);
					cram[s*BLKW + en*ENTW + 1] = mk_ctl(vs, ve, hs);
				end else begin
					// parked sprite: terminator, exactly as Hybris leaves
					// sprites 6 and 7 on the reward screen.
					cram[s*BLKW + en*ENTW + 0] = 16'h0000;
					cram[s*BLKW + en*ENTW + 1] = 16'h0000;
				end
				for (w = 2; w < ENTW; w = w + 1)
					cram[s*BLKW + en*ENTW + w] = 16'hA500 + s*16 + en;
			end
			for (w = 8*ENTW; w < BLKW; w = w + 1)
				cram[s*BLKW + w] = 16'h0000;    // list terminator + tail
		end
	end
endtask

// Copper-style pointer reload during vblank: 16 consecutive register writes
// starting at hpos $80 on line 20 of every frame -- clear of the sprite DMA
// window ($31..$71) and clear of the vblend refetch line ($19).
//   SPRnPTH = $120+4n -> reg_address_in = {4'h9, n, 1'b0}, data[4:0]  = $01
//   SPRnPTL = $122+4n -> reg_address_in = {4'h9, n, 1'b1}, data[15:1] = n*$200
reg [4:0] cop_i = 5'd16;
always @(posedge clk) if (clk7_en) begin
	if (vpos == 11'd20 && hpos == 9'h080) cop_i <= 5'd0;
	else if (cop_i < 5'd16)               cop_i <= cop_i + 5'd1;

	if (cop_i < 5'd16) begin
		cop_addr <= {4'h9, cop_i[3:1], cop_i[0]};
		cop_data <= cop_i[0] ? {3'd0, cop_i[3:1], 10'd0} : 16'h0001;
	end else begin
		cop_addr <= 8'hFF;
		cop_data <= 16'h0000;
	end
end

initial begin
	for (i = 0; i < 8; i = i + 1) begin
		ref_vstart[i] = 10'd0; ref_vstop[i] = 10'd0;
		ref_dma[i] = 1'b0; ref_sprdma[i] = 1'b0; ref_svstop[i] = 1'b0;
		ref_ptr[i] = 20'd0;
	end
end

endmodule


// ===========================================================================
//                                   TOP
// ===========================================================================
module tb_sprite_mux_load;

parameter integer FRAMES  = 16;
parameter integer STAGGER = 0;   // per-sprite VSTART stagger in lines

integer tb_errs = 1;

initial begin
	#1400000000 $fatal(1, "tb_sprite_mux_load: watchdog timeout");
end

logic clk = 0;
initial forever #17.6 clk = ~clk;      // ~28.375 MHz

logic reset_n = 1'b0;
logic reset   = 1'b1;
logic run     = 1'b0;

wire clk7_en, clk7n_en, c1, c3, cck;

amiga_clk u_clk (
	.clk_28 (clk), .clk7_en (clk7_en), .clk7n_en (clk7n_en),
	.c1 (c1), .c3 (c3), .cck (cck), .eclk (), .reset_n (reset_n)
);

wire [8:0]  hpos;
wire [10:0] vpos;
wire        vbl, vblend, eol, eof;

agnus_beamcounter u_bc (
	.clk (clk), .clk7_en (clk7_en), .reset (reset), .cck (cck),
	.ntsc (1'b0), .aga (1'b0), .ecs (1'b0), .a1k (1'b0),
	.data_in (16'h0000), .data_out (), .reg_address_in (8'hFF),
	.hpos (hpos), .vpos (vpos),
	._hsync (), ._vsync (), .field1 (), .lace (), ._csync (),
	.hblank (), .vblank (), .vbl (vbl), .vblend (vblend),
	.eol (eol), .eof (eof), .vbl_int (),
	.htotal_out (), .harddis_out (), .varbeamen_out ()
);

// ------------------------------------------------------------- the four arms
wire [31:0] e1, e3, e6, e8;
wire [31:0] s1, s3, s6, s8;
wire [31:0] p1, p3, p6, p8;
wire [31:0] d1, d3, d6, d8;

spr_env #(.NACT(1), .STAG(STAGGER)) env1 (.clk(clk), .clk7_en(clk7_en), .reset(reset), .hpos(hpos),
	.vpos(vpos), .vbl(vbl), .vblend(vblend), .run(run),
	.errs(e1), .slots_checked(s1), .fetches_pos(p1), .fetches_dat(d1));
spr_env #(.NACT(3), .STAG(STAGGER)) env3 (.clk(clk), .clk7_en(clk7_en), .reset(reset), .hpos(hpos),
	.vpos(vpos), .vbl(vbl), .vblend(vblend), .run(run),
	.errs(e3), .slots_checked(s3), .fetches_pos(p3), .fetches_dat(d3));
spr_env #(.NACT(6), .STAG(STAGGER)) env6 (.clk(clk), .clk7_en(clk7_en), .reset(reset), .hpos(hpos),
	.vpos(vpos), .vbl(vbl), .vblend(vblend), .run(run),
	.errs(e6), .slots_checked(s6), .fetches_pos(p6), .fetches_dat(d6));
spr_env #(.NACT(8), .STAG(STAGGER)) env8 (.clk(clk), .clk7_en(clk7_en), .reset(reset), .hpos(hpos),
	.vpos(vpos), .vbl(vbl), .vblend(vblend), .run(run),
	.errs(e8), .slots_checked(s8), .fetches_pos(p8), .fetches_dat(d8));

// ===========================================================================
// DIRECT MULTIPLEX INSTRUMENTS (env6; sprsel is env-independent anyway)
// ===========================================================================
wire [2:0] sprsel  = env6.u_spr.sprsel;
wire [2:0] dsprite = env6.u_spr.sprite;
wire       win     = (hpos[2:1] == 2'b01);

reg  [7:0] scan_mask = 8'h00;
reg        win_d     = 1'b0;
reg  [2:0] sprsel_d  = 3'd0;

integer win_n = 0, win_incomplete = 0, win_dup = 0;
integer match_n = 0, match_min = 1000, match_max = 0;
integer scan_stall = 0;
integer last_latch_t = 0, margin_min = 1000000, margin_max = 0, margin_n = 0;
integer clk_t = 0;

always @(posedge clk) clk_t    <= clk_t + 1;
always @(posedge clk) sprsel_d <= sprsel;

always @(posedge clk) if (run && !reset) begin
	if (sprsel === sprsel_d) scan_stall <= scan_stall + 1;

	if (win) begin
		if (!win_d) begin
			scan_mask <= (8'h01 << sprsel);
			match_n   <= (dsprite === sprsel) ? 1 : 0;
		end else begin
			if (scan_mask[sprsel]) win_dup <= win_dup + 1;
			scan_mask <= scan_mask | (8'h01 << sprsel);
			if (dsprite === sprsel) match_n <= match_n + 1;
		end
		if (dsprite === sprsel) last_latch_t <= clk_t;
	end else if (win_d) begin
		win_n <= win_n + 1;
		if (scan_mask !== 8'hFF) win_incomplete <= win_incomplete + 1;
		if (match_n < match_min) match_min <= match_n;
		if (match_n > match_max) match_max <= match_n;
	end
	win_d <= win;

	// first use of the latched value = the sprite's POS/DATA slot
	if (clk7_en && env6.tb_enable && hpos[1:0]==2'b01 && hpos[2]) begin
		margin_n <= margin_n + 1;
		if ((clk_t - last_latch_t) < margin_min) margin_min <= clk_t - last_latch_t;
		if ((clk_t - last_latch_t) > margin_max) margin_max <= clk_t - last_latch_t;
	end
end

// ------------------------------------------- scan phase at bus-write time
// Every sprpos/sprctl bank write happens on a clk7_en edge. Which scan slot is
// the shared comparator reading at that instant? If a write can coincide with
// sprsel == the sprite being written, the comparator sees pre-write data for
// one CCK (distributed-RAM read-during-write). This measures how often that
// happens and on which slots.
integer wr_phase [0:7];
integer wr_same  = 0;
integer wr_tot   = 0;
integer j;
initial for (j = 0; j < 8; j = j + 1) wr_phase[j] = 0;

wire spr_wr = env6.clk7_en && (env6.reg_address_in[8:6] == 3'b101) &&
              (env6.reg_address_in[2] == 1'b0);
wire [2:0] spr_wr_sel = env6.ackdma ? env6.tb_sprite : env6.reg_address_in[5:3];

always @(posedge clk) if (run && !reset && spr_wr) begin
	wr_tot         <= wr_tot + 1;
	wr_phase[sprsel] <= wr_phase[sprsel] + 1;
	if (sprsel === spr_wr_sel) wr_same <= wr_same + 1;
end

// ------------------------------------------------------------ liveness guard
integer lines_seen = 0, frames_seen = 0;
reg [10:0] vpos_q = 11'd0;
always @(posedge clk) begin
	vpos_q <= vpos;
	if (!reset && vpos !== vpos_q) lines_seen <= lines_seen + 1;
end
always @(posedge clk) if (clk7_en && eof) frames_seen <= frames_seen + 1;

// ===========================================================================
integer f, k;
integer base_i;

task seed_all;
	begin
		env1.u_spr.sprsel = 3'd0; env1.u_spr.sprite = 3'd0;
		env3.u_spr.sprsel = 3'd0; env3.u_spr.sprite = 3'd0;
		env6.u_spr.sprsel = 3'd0; env6.u_spr.sprite = 3'd0;
		env8.u_spr.sprsel = 3'd0; env8.u_spr.sprite = 3'd0;
		env1.u_spr.sprvstop = 1'b0; env1.u_spr.sprdmastate = 1'b0; env1.u_spr.enable = 1'b0;
		env3.u_spr.sprvstop = 1'b0; env3.u_spr.sprdmastate = 1'b0; env3.u_spr.enable = 1'b0;
		env6.u_spr.sprvstop = 1'b0; env6.u_spr.sprdmastate = 1'b0; env6.u_spr.enable = 1'b0;
		env8.u_spr.sprvstop = 1'b0; env8.u_spr.sprdmastate = 1'b0; env8.u_spr.enable = 1'b0;
		for (k = 0; k < 8; k = k + 1) begin
			env1.u_spr.dmastate_mem[k] = 1'b0; env3.u_spr.dmastate_mem[k] = 1'b0;
			env6.u_spr.dmastate_mem[k] = 1'b0; env8.u_spr.dmastate_mem[k] = 1'b0;
			env1.u_spr.sprpos[k]  = 8'd0;  env3.u_spr.sprpos[k]  = 8'd0;
			env6.u_spr.sprpos[k]  = 8'd0;  env8.u_spr.sprpos[k]  = 8'd0;
			env1.u_spr.sprposh[k] = 1'b0;  env3.u_spr.sprposh[k] = 1'b0;
			env6.u_spr.sprposh[k] = 1'b0;  env8.u_spr.sprposh[k] = 1'b0;
			env1.u_spr.sprctl[k]  = 12'd0; env3.u_spr.sprctl[k]  = 12'd0;
			env6.u_spr.sprctl[k]  = 12'd0; env8.u_spr.sprctl[k]  = 12'd0;
			env1.u_spr.sprpth[k]  = 5'd0;  env3.u_spr.sprpth[k]  = 5'd0;
			env6.u_spr.sprpth[k]  = 5'd0;  env8.u_spr.sprpth[k]  = 5'd0;
			env1.u_spr.sprptl[k]  = 15'd0; env3.u_spr.sprptl[k]  = 15'd0;
			env6.u_spr.sprptl[k]  = 15'd0; env8.u_spr.sprptl[k]  = 15'd0;
		end
	end
endtask

task build_all (input [8:0] base);
	begin
		env1.build_lists(base); env3.build_lists(base);
		env6.build_lists(base); env8.build_lists(base);
	end
endtask

task wait_vpos (input [10:0] target);
	begin
		while (vpos !== target) @(posedge clk);
		while (vpos === target) @(posedge clk);
	end
endtask

initial begin
	reset = 1'b1; reset_n = 1'b0;
	repeat (40) @(posedge clk);
	reset_n = 1'b1;
	repeat (40) @(posedge clk);
	reset = 1'b0;

	// agnus_beamcounter's hpos/vpos and agnus_spritedma's sprsel/sprite have no
	// reset term. On the FPGA Quartus powers them up at 0; in simulation they
	// start X and never recover. Seed them exactly as the device comes up.
	// Sim hygiene, not a behavioural change.
	u_bc.hpos[8:1] = 8'd0;
	u_bc.vpos      = 11'd0;
	seed_all;
	repeat (8) @(posedge clk);

	build_all(9'd105);
	env1.spren = 1'b1; env3.spren = 1'b1; env6.spren = 1'b1; env8.spren = 1'b1;

	// one settling frame (pointer reload + first vblend refetch), then arm.
	wait_vpos(11'd300);
	wait_vpos(11'd30);
	run = 1'b1;

	for (f = 0; f < FRAMES; f = f + 1) begin
		wait_vpos(11'd5);                     // deep inside vblank
		base_i = 105 - f*7;
		if (base_i < 0) base_i = base_i + 260;
		build_all(base_i[8:0]);
		wait_vpos(11'd300);
	end

	report;
	$finish;
end

task report;
	integer tot;
	begin
		tot = e1 + e3 + e6 + e8;
		$display("");
		$display("=============== tb_sprite_mux_load ===============");
		$display(" stimulus : measured Hybris reward-screen sprite lists");
		$display("            8 entries/sprite, VSTART=base+22*i, VSTOP=+8,");
		$display("            base scrolled every frame, %0d frames, stagger=%0d", FRAMES, STAGGER);
		$display("");
		$display(" LIVENESS");
		$display("   scanlines advanced       : %0d", lines_seen);
		$display("   eof pulses               : %0d", frames_seen);
		$display("   sprite DMA slots checked : %0d / %0d / %0d / %0d", s1, s3, s6, s8);
		$display("   POS/CTL fetches expected : %0d / %0d / %0d / %0d", p1, p3, p6, p8);
		$display("   DATA/DATB fetches expctd : %0d / %0d / %0d / %0d", d1, d3, d6, d8);
		$display("");
		$display(" MULTIPLEX SCAN");
		$display("   latch windows observed                  : %0d", win_n);
		$display("   windows NOT covering all 8 sprsel slots  : %0d", win_incomplete);
		$display("   windows with a DUPLICATE sprsel slot     : %0d", win_dup);
		$display("   sprite==sprsel samples per window   min  : %0d", match_min);
		$display("                                       max  : %0d", match_max);
		$display("   clk edges where sprsel did not advance   : %0d", scan_stall);
		$display("   latch -> first use margin (28MHz clks)   : min %0d  max %0d  (n=%0d)",
		         margin_min, margin_max, margin_n);
		$display("");
		$display("   SPRxPOS/CTL bank writes seen (N=6 arm)   : %0d", wr_tot);
		$display("   sprsel histogram at write time           : %0d %0d %0d %0d %0d %0d %0d %0d",
		         wr_phase[0], wr_phase[1], wr_phase[2], wr_phase[3],
		         wr_phase[4], wr_phase[5], wr_phase[6], wr_phase[7]);
		$display("   writes coinciding with sprsel == target  : %0d", wr_same);
		$display("");
		$display(" EQUIVALENCE vs 8-PARALLEL REFERENCE  (mismatched slots)");
		$display("   1 active sprite  : %0d", e1);
		$display("   3 active sprites : %0d", e3);
		$display("   6 active sprites : %0d   <- measured Hybris load", e6);
		$display("   8 active sprites : %0d", e8);
		$display("");
		if (s6 == 0 || d6 == 0 || p6 == 0 || lines_seen < 313) begin
			$display(" VERDICT: VACUOUS -- the bench did not run the engine.");
			$display("          (slots=%0d pos=%0d dat=%0d lines=%0d)", s6, p6, d6, lines_seen);
			tb_errs = 1;
		end else if (tot == 0 && win_incomplete == 0 && win_dup == 0 &&
		             match_min == 1 && match_max == 1) begin
			$display(" VERDICT: PASS -- the time-multiplexed sprite select is");
			$display("          bit-exact against 8 parallel comparators at every");
			$display("          sprite count, and the scan covers all 8 slots in");
			$display("          every latch window with no count dependence.");
			tb_errs = 0;
		end else begin
			$display(" VERDICT: FAIL -- %0d mismatched slots, %0d incomplete scan windows,",
			         tot, win_incomplete);
			$display("          %0d duplicated slots, match/window %0d..%0d.",
			         win_dup, match_min, match_max);
			tb_errs = tot + win_incomplete + win_dup +
			          ((match_min != 1 || match_max != 1) ? 1 : 0);
		end
		$display("==================================================");
		$display("");
	end
endtask

endmodule
